# Generated by Django 4.0.5 on 2022-07-14 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(db_column='admin_id', max_length=20, unique=True)),
                ('password', models.CharField(db_column='password', max_length=4096)),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('updatedAt', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_id', models.CharField(db_column='t_id', max_length=20, unique=True)),
                ('lab_name', models.CharField(db_column='lab_name', max_length=100)),
                ('s_core_time_start', models.TimeField(db_column='s_core_time_start', null=True)),
                ('s_core_time_end', models.TimeField(db_column='s_core_time_end', null=True)),
                ('m_core_time_start', models.TimeField(db_column='m_core_time_start', null=True)),
                ('m_core_time_end', models.TimeField(db_column='m_core_time_end', null=True)),
                ('d_core_time_start', models.TimeField(db_column='d_core_time_start', null=True)),
                ('d_core_time_end', models.TimeField(db_column='d_core_time_end', null=True)),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('updatedAt', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'laboratory',
            },
        ),
        migrations.CreateModel(
            name='MajorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('m_id', models.CharField(db_column='m_id', max_length=5)),
                ('m_name', models.CharField(db_column='m_name', max_length=50)),
                ('first_half_term', models.IntegerField(db_column='first_half_term', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('second_half_term', models.IntegerField(db_column='second_half_term', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('total_term', models.IntegerField(db_column='total_term', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('updatedAt', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(db_column='u_id', max_length=20)),
                ('ipaddr', models.CharField(db_column='ipaddr', max_length=50, null=True)),
                ('memo', models.TextField(db_column='memo', null=True)),
                ('comment', models.TextField(db_column='comment', null=True)),
                ('createdAt', models.DateTimeField(db_column='createdAt', null=True)),
                ('updatedAt', models.DateTimeField(db_column='updatedAt', null=True)),
                ('s_notice', models.BooleanField(default=False)),
                ('t_notice', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(db_column='u_id', max_length=20, unique=True)),
                ('u_name', models.CharField(db_column='name', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=4096)),
                ('t_id', models.CharField(db_column='t_id', max_length=15)),
                ('email', models.EmailField(db_column='email', max_length=254, null=True)),
                ('major', models.CharField(db_column='major', max_length=100)),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('updatedAt', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_id', models.CharField(db_column='t_id', max_length=20, unique=True)),
                ('t_name', models.CharField(db_column='name', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=4096)),
                ('email', models.EmailField(db_column='email', max_length=254, null=True)),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('updatedAt', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
